from os import path

TEST_PACKAGE = "tests"
JAVA_TEST_PROJECT = path.join(TEST_PACKAGE, "java")
LITEMATIC_DIRECTORY = path.join(TEST_PACKAGE, "litematics")
VALID_LITEMATIC_DIRECTORY = path.join(LITEMATIC_DIRECTORY, "valid")
FILTER_LITEMATIC_DIRECTORY = path.join(LITEMATIC_DIRECTORY, "filter")
